// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211119205958_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9527649d-aa37-4d91-8fb1-c984eea6c25f"),
                            Description = "Channel for AngularJS and Angular 11",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("b452369b-51cf-4288-ba3d-0a4d781afdc1"),
                            Description = "Channel for ReactJS",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("b1753190-21cf-4c88-9df8-e1da1a3210dd"),
                            Description = "Channel for NetCore, Net 5 and Net Framework",
                            Name = "Angular"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
